### ISSUE TITLE
chmod them and change group if exists

### ISSUE THREAD

**Issue by evadogstar** [tasket/Qubes-VM-hardening#3]
If some files/dirs already exists need to change usergroup and warn user.

**Comment by tasket** [comment]
I think you mean there is a risk that already-existing scripts could be malware. Correct?

Can you explain what changing the usergroup would accomplish?

**Comment by evadogstar** [comment]
Your protection based on creating not writable dirs for regular user. But if dir already exists `touch dir` will not solve the problem, because dir will still be writable by user after failed `touch dir` command.

**Comment by tasket** [comment]
`touch` and `makedir` only ensure that the files/dirs exist for the `chattr +i` command.

**Comment by evadogstar** [comment]
Got it, sorry, it's my bad attention or weariness
