### ISSUE TITLE
does not cover /usr/local/etc

### ISSUE THREAD

**Issue by adrelanos** [tasket/Qubes-VM-hardening#30]
Whonix makes extensive use of /usr/local/etc (/usr/local is stored in /rw). (I find that folder closer to FHS than inventing /rw/config.)

**Comment by tasket** [comment]
I think you're saying Whonix needs this whitelisted by default?

**Comment by adrelanos** [comment]
No. While some Whonix packages parse that folder by default, nothing is
using it by default. Only users could put configuration files there if
they don't want to add them in TemplateVM.

Files there should be seen as potential malware hooks unless somehow (I
don't fully understand all yet) whitelisted by the user.

**Comment by tasket** [comment]
According to the threat model (malware being added to /rw in template-based appvm) we're really talking about /rw/usrlocal which is one of the three /rw dirs that are sanitized by default.

**Comment by adrelanos** [comment]
Alright, therefore invalid bug report.
