### ISSUE TITLE
Labeled configurations

### ISSUE THREAD

**Issue by tasket** [tasket/Qubes-VM-hardening#35]
Allow user to define a configuration (whitelist, etc.) in '/etc/default/vms/@tags/' using *label* names instead of actual VM names.

This allows setup of a generic "vpn" config, for example, which the user can link to any VM they think requires the "vpn" config.

Linking could be done by specifying Qubes service names like `vm-boot-tag-vpn`.

**Comment by adrelanos** [comment]
How can one set a label in Qubes and how can the inside of the VM know the label?

**Comment by tasket** [comment]
@adrelanos Labels (actually 'tags') are known via Qubes services with a specific prefix ([see here](https://github.com/tasket/Qubes-VM-hardening/blob/8f8e7e6595677a22f8171c301566cb3b4450c0e5/vm-boot-protect.sh#L153)). This is now covered in the Readme.
