### ISSUE TITLE
debian-10 vpn malfunction vm-boot-protect

### ISSUE THREAD

**Issue by pugege** [tasket/Qubes-VM-hardening#40]
With most recent master versions Aug 16 & Aug 18, an enabled vm-boot-protect service prevents a debian-10 vpnvm with vpn-handler-openvpn service from starting connection.
If vm-boot-protect service is disabled vpnvm functions normally. Previous earlier
new4 and master versions worked without problems on my system

**Comment by tasket** [comment]
@pugege Should be fixed now. Thanks for the report!
