### ISSUE TITLE
Archlinux

### ISSUE THREAD

**Issue by netizen0** [tasket/Qubes-VM-hardening#44]
Can you help me figure out how to replace the `configure-sudo-prompt` script for archlinux?

I tried commenting out the check for debian_version, and replacing the common-auth filenames in the script with system-auth, but it is more complicated then that apparently because I get  messge like:

> Permission denied: Is your account locked?

**Comment by netizen0** [comment]
To clarify, I was getting that message when I had tried running `sudo su` after running the script, and I had already done the steps in dom0 to enable the popup for other vms.

I have since tried to alter the script some more, and I am getting the popup, but commands do not succeed  when I click OK on the popup in dom0.

Here is the script as I have updated it for archlinux (doesn't work yet)

```
#!/bin/bash
# From https://github.com/tasket/Qubes-VM-hardening

set -e
[ `id -u` -eq 0 ] || exit


if [ ! -e /etc/sudoers.d/qubes ]; then
    echo "The 'qubes-core-agent-passwordless-root' package does not appear"
    echo "to be present or configured; sudo autoconfiguration skipped."
    exit 0
fi


if [ "$1" = "--force" ]; then
    force=1
else
    force=0
fi

if grep -q '^auth .* dom0\squbes\.VMAuth' /etc/pam.d/system-auth && [ $force = 0 ]; then
    echo "System appears already configured for sudo prompts."
    echo "To force re-configuration run 'configure-sudo-prompt --force'."
    exit 0
fi


echo -e "\n--+  Enable yes/no authentication prompt for sudo  +--
Warning: Before opting for this change a backup or clone
should me made of this template!"
if [ $force = 0 ]; then
    read -p "Configure sudo authentication prompt now? (y/n): " answer
fi
if [[ $answer == @(y|Y) ]] || [ $force = 1 ]; then

    mv -fb /etc/pam.d/system-auth /etc/pam.d/system-auth~
    cat >/etc/pam.d/system-auth <<_EOF
auth  [success=1 default=ignore]  pam_exec.so seteuid /usr/lib/qubes/qrexec-client-vm dom0 qubes.VMAuth /bin/grep -q ^1$
account optional	pam_permit.so
account required	pam_env.so

account [success=1 new_authtok_reqd=done default=ignore]	pam_unix.so
account optional	pam_permit.so
account required	pam_time.so

password	[success=1 default=ignore]	pam_unix.so obscure sha512
password	optional	pam_permit.so

session required	pam_limits.so
session required	pam_unix.so
session optional	pam_permit.so
_EOF


#    sed -i 's/^user ALL=(ALL) NOPASSWD: ALL/user ALL=(ALL) ALL/' /etc/sudoers.d/qubes
    sed -i 's/^user/#user/' /etc/sudoers.d/qubes
    echo 'user ALL=(ALL) ALL' >>/etc/sudoers.d/qubes

    sed -ri 's/^(auth[[:space:]]+required[[:space:]]+pam_shells\.so)/auth	\[success=ok new_authtok_reqd=ok ignore=ignore user_unknown=bad default=die\]	pam_shells.so/' /etc/pam.d/system-login

    mv -f /etc/polkit-1/rules.d/00-qubes-allow-all.rules \
      /etc/polkit-1/rulesd_00-qubes-allow-all.rules.bak || true
    mv -f /etc/polkit-1/localauthority/50-local.d/qubes-allow-all.pkla \
      /etc/polkit-1/localauthority_50-locald_qubes-allow-all.pkla.bak || true

    echo "Done."

    echo '
Next.... Enable auth prompts in dom0 with the following commands:
  [user@dom0 ~]$ sudo su -
  [root@dom0 /]# echo "/usr/bin/echo 1" >/etc/qubes-rpc/qubes.VMAuth
  [root@dom0 /]# echo "\$anyvm dom0 ask,default_target=dom0" \
    >/etc/qubes-rpc/policy/qubes.VMAuth

'
fi
```

**Comment by tasket** [comment]
@netizen0 I'm not familiar with Arch, so can only guess...

1. Look at the [vm-sudo doc](https://www.qubes-os.org/doc/vm-sudo/#replacing-passwordless-root-access-with-dom0-user-prompt) and notice how different the Fedora instructions are vs the Debian ones. The filenames are different, and the Fedora ones may be closer to or same as Arch. There's also a good chance Arch has docs detailing how sudo and PAM auth are configured.

2. Examine the contents of the `qubes-core-agent-passwordless-root` package. That should provide clues about which files/paths have to be modified.

3. If you can't get it to work in the short term, a functional/security equivalent can be achieved by uninstalling `qubes-core-agent-passwordless-root` package from a fresh template clone. However, it will be less convenient to run anything with privs bc that will have to be done from dom0 like `qvm-run -u root vmname cmd`.

**Comment by netizen0** [comment]
My fault, this script worked once I fixed the mistake at the beginning of system-auth file. I had account on the second two lines instead of auth.
