### ISSUE TITLE
Add whitelists to retain some files in /rw/config etc

### ISSUE THREAD

**Issue by tasket** [tasket/Qubes-VM-hardening#5]
Currently the protection service deletes all /rw system stuff:
rm -rf config usrlocal bind-dirs

Instead, use whitelist files to create exceptions in the removal process.

**Comment by tasket** [comment]
@adrelanos Whitelist feature now available in systemd branch. Suggestions for Tor?

**Comment by tasket** [comment]
I don't like the current whitelist code -- can't handle pattern matching or whole dirs -- so I'm rewriting it today.

New whitelisting will feed lists to `cp` and should support both dirs and globbing.

**Comment by adrelanos** [comment]
> Currently the protection service deletes all /rw system stuff:
> rm -rf config usrlocal bind-dirs

Perhaps in that case rather just prevent bind-dirs from starting? Seems much better than wiping user data. Could be a bad surprise for many users.

(Even as a quick fix, rather moving it elsewhere would be nicer than wiping.)

 (This might require small changes to bind-dirs so it easily does nothing when some file exists or perhaps its own systemd unit that then does not start it due to some condition file existing.)

**Comment by tasket** [comment]
@adrelanos I wouldn't know how to prevent bind-dirs from starting (its called from the mount script), and that would still leave ../config. Maybe replacing the mount-dirs service somehow with this service would be necessary.

I've been thinking about backups, and have tried some simple strategies. `cp` will version them but there's not limit, unfortunately. Current version just moves them to dir with a 'BAK-' prefix, but old BAK- gets deleted. Was also thinking "backup if no BAK- dirs exist, otherwise delete" had a better chance of preserving files the user added. Let me know if you have a preference.

Ultimately it will be a matter a documentation and user precaution, since the root-related functions will encounter auto re-generated scripts and something somewhere has to get deleted. One alternative for the user could be to whitelist those dirs but monitor contents with hash check feature instead; another is only use the /home protection feature.

Thanks for the input!

**Comment by adrelanos** [comment]
> @adrelanos I wouldn't know how to prevent bind-dirs from starting (its called from the mount script)

`bind-dirs.sh` needs to be patched.

Related to [`Require script to run immed. after /rw mount`](https://groups.google.com/d/msg/qubes-devel/kr_SGqFe14Y/jhWX-UCqAQAJ). The conclusion from there was, use [`qvm-service`](https://www.qubes-os.org/doc/qubes-service/).

Modify [`bind-dirs.sh`](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/vm-systemd/bind-dirs.sh). From:

```

prerequisite() {
   if ! is_rwonly_persistent ; then
      true "No TemplateBasedVM detected. Exiting."
      exit 0
   fi
}
```

Using https://www.qubes-os.org/doc/qubes-service/. To:

```
if [ -e /var/run/qubes-service/bind-dirs-skip-programatic ]; then
      true "/var/run/qubes-service/bind-dirs-skip-programatic exists. Exiting."
      exit 0
fi

if [ -e /var/run/qubes-service/bind-dirs-skip ]; then
      true "/var/run/qubes-service/bind-dirs-skip exists. Exiting."
      exit 0
fi
```

Then you could just create /var/run/qubes-service/bind-dirs-skip-programatic before mount-dirs.

All untested.

(I don't think both users manually and programs such as qubes-vm-hardening should use the same qvm-service status file. Makes debugging harder.)

That's the long term clean fix.

The short term workaround

Ship `/usr/lib/qubes-bind-dirs.d/40_qubes-vm-hardening.conf` or so and add the improved `prerequisite` function there.

Does that make sense?

> and that would still leave ../config

Perhaps patch all scripts using ../config to adhere qvm-service so you can disable these as well?

**Comment by tasket** [comment]
@adrelanos Taking time to wrap my head around your interesting suggestions, but it feels difficult for one main reason... attempts to do almost anything re: service modifications in Debian 8 causes startup failures. I can add my service "Before=qubes-mount-dirs" and it fails even if script is only "exit 0"; same if I use .conf files to modify. Of course, this means even creating files in /var/run is blocked. Head is full of "can't do that..."

Two days of trying and I'm ready to move on to Debian 9 which responds much better.

So... I could put a .conf in /usr/lib/qubes-bind-dirs.d. But this is dependant on how Qubes orders events going into the future; a change could break it. I feel like the current way of running a service before mount-dirs is more explicit and correct; and at least it already works on Stretch. It also allows other features like checksumming or replacement to execute within the script in a tightly defined sequence. (But the .conf hook may lead to a basic workaround for Debian 8 users.)

Patching all relevant scripts using *.d sounds like too many moving targets, and in the user's mind makes the purpose and efficacy of the feature/service unclear... which is to protect the VM startup environment from the contents of /rw just as the latter comes online. A clear intervention point is known. OTOH, it is something to consider if users want much more fine-grained control and/or Qubes wants to implement it internally.

If I have missed an angle here, please let me know.
